# Generated by Django 5.2.12 on 2026-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chefs/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HERO', 'Hero/Portada'), ('ABOUT', 'Sobre el Evento'), ('CHEFS', 'Sección de Chefs'), ('TICKETS', 'Entradas/Tickets')], max_length=10, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('background_image', models.ImageField(upload_to='sections/')),
            ],
        ),
    ]
