# Generated by Django 5.2.12 on 2026-03-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=20)),
                ('info', models.TextField(help_text='Lo que incluye')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='eventsection',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='eventsection',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='sections/'),
        ),
        migrations.AlterField(
            model_name='eventsection',
            name='type',
            field=models.CharField(choices=[('HERO', 'Hero/Portada'), ('INFO', 'Información General'), ('TICKETS', 'Sección de Tickets')], max_length=10, unique=True),
        ),
    ]
